# 设置单个域名下多个目录,根据后缀不同进行访问,VUE许要修改的配置

# vite.config.js:
# 原配置 
publicPath: process.env.NODE_ENV === "production" ? "/" : "/",

# 新配置
publicPath: process.env.NODE_ENV === "production" ? "/b/" : "/",


# router/index.js

# 原配置
export default new Router({
  mode: 'history', // 去掉url中的#
  scrollBehavior: () => ({ y: 0 }),
  routes: constantRoutes
})

# 新配置
export default new Router({
  mode: 'history', // 去掉url中的#
  base: 'b', // 基础路径进行调整
  scrollBehavior: () => ({ y: 0 }),
  routes: constantRoutes
})

# env.production:根据接口调用地址是否修改而修改
VUE_APP_BASE_API = '/api-b'

# 如果页面中有类似location.href = '/index';这种直接跳转页面的语句,也要修改为/b/index.html等